### PR TITLE
feat: Added GitHub action pipeline to build and publish Flint.Example Docker image to GitHub container registry

### PR DESCRIPTION
**Pull request by iamrajiv**
Related: moja-global/FLINT-UI#71

### CODE REVIEW

**Comment by iamrajiv** [comment]
@aornugent @shubhamkarande13

**Comment by shubhamkarande13** [comment]
Looks good @iamrajiv ! 🎉

**Comment by aornugent** [comment]
@asmijafar20 - is this aligned with your latest release for FLINTcloud?

**Comment by asmijafar20** [comment]
> @asmijafar20 - is this aligned with your latest release for FLINTcloud?

Yes, it's fine.

**Pull request merged**
